# img base:versao
FROM  nginx:latest 
# saida echo -> caminho da pasta
RUN echo '<h1>Hello World!2<h1>' > /usr/share/nginx/html/index.html

# Constroi img das camadas do nginx e adicionar uma nova do comando run 